name = "2fanvior"
main = ".open-next/worker.js"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[build]
command = "npm run build && npx @opennextjs/cloudflare build"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "fanvior-db"
database_id = "ed0f91eb-d0da-49ed-a704-d9f83d5c5358"
